--- 
abstract: transform a subroutine that operates on C<$_> into
author: 
  - Jonathan Rockway C<< jrockway@cpan.org >>
build_requires: 
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: Perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Sub-AliasedUnderscore
no_index: 
  directory: 
    - inc
    - t
version: 0.02
